### ISSUE TITLE
Bug: Nuke 13 Support major blocker for client

### ISSUE THREAD

**Issue by gpl-nickallevato** [aws-deadline/deadline-cloud-for-nuke#184]
### Expected Behaviour

Expect to install Nuke submission script and it work with Nuke 13.

### Current Behaviour

Nuke 13 errors with the following errors:

Failed to load deadline.nuke_submitter. Reason:
Traceback (most recent call last):
  File "C:\Users\miggy\Downloads\aws_deadline_cloud\deadline-cloud-for-nuke\src/menu.py", line 16, in <module>
    from deadline.nuke_submitter import (
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter\__init__.py", line 5, in <module>
    from .deadline_submitter_for_nuke import show_nuke_render_submitter_noargs
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter\deadline_submitter_for_nuke.py", line 12, in <module>
    from deadline.client.api import get_deadline_cloud_library_telemetry_client
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api\__init__.py", line 37, in <module>
    from ._loginout import login, logout
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api\_loginout.py", line 15, in <module>
    from ._session import (
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api\_session.py", line 16, in <module>
    import boto3  # type: ignore[import]
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\boto3\__init__.py", line 17, in <module>
    from boto3.session import Session
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\boto3\session.py", line 17, in <module>
    import botocore.session
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\botocore\session.py", line 26, in <module>
    import botocore.client
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\botocore\client.py", line 151
    if auth := service_model.metadata.get('auth'):
             ^
SyntaxError: invalid syntax

And:

Failed to load deadline.nuke_submitter. Reason:
Traceback (most recent call last):
  File "C:\Users\miggy\Downloads\aws_deadline_cloud\deadline-cloud-for-nuke\src/menu.py", line 16, in <module>
    from deadline.nuke_submitter import (
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter\__init__.py", line 5, in <module>
    from .deadline_submitter_for_nuke import show_nuke_render_submitter_noargs
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter\deadline_submitter_for_nuke.py", line 12, in <module>
    from deadline.client.api import get_deadline_cloud_library_telemetry_client
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api\__init__.py", line 37, in <module>
    from ._loginout import login, logout
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api\_loginout.py", line 15, in <module>
    from ._session import (
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api\_session.py", line 76, in <module>
    @lru_cache
  File "C:\Program Files\Nuke13.2v9\lib\functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

And: 

Failed to load deadline.nuke_submitter. Reason:
Traceback (most recent call last):
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke/menu.py", line 16, in <module>
    from deadline.nuke_submitter import (
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter\__init__.py", line 5, in <module>
    from .deadline_submitter_for_nuke import show_nuke_render_submitter_noargs
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter\deadline_submitter_for_nuke.py", line 15, in <module>
    from deadline.client.ui.dialogs.submit_job_to_deadline_dialog import (  # type: ignore
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\ui\dialogs\submit_job_to_deadline_dialog.py", line 41, in <module>
    from ..widgets.host_requirements_tab import HostRequirementsWidget
  File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\ui\widgets\host_requirements_tab.py", line 10, in <module>
    from qtpy.QtGui import QFont, QValidator, QIntValidator, QBrush, QIcon, QRegularExpressionValidator  # type: ignore
ImportError: cannot import name 'QRegularExpressionValidator' from 'qtpy.QtGui' (C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\qtpy\QtGui.py)

### Reproduction Steps

Install Deadline/Nuke submitter using development.md instructions.

Then manually 'patch' the walrus operator to use non-walrus syntax.
Then you run into the QT depenency issue.

### Code Snippet

None.

**Comment by eherozhao** [comment]
Thanks for your reply @nickgpltech. The team will look into it and reproduce the issue you saw and give you the update then.

**Comment by eherozhao** [comment]
> ### Expected Behaviour
> Expect to install Nuke submission script and it work with Nuke 13.
> 
> ### Current Behaviour
> Nuke 13 errors with the following errors:
> 
> Failed to load deadline.nuke_submitter. Reason: Traceback (most recent call last): File "C:\Users\miggy\Downloads\aws_deadline_cloud\deadline-cloud-for-nuke\src/menu.py", line 16, in from deadline.nuke_submitter import ( File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter__init__.py", line 5, in from .deadline_submitter_for_nuke import show_nuke_render_submitter_noargs File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter\deadline_submitter_for_nuke.py", line 12, in from deadline.client.api import get_deadline_cloud_library_telemetry_client File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api__init__.py", line 37, in from ._loginout import login, logout File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api_loginout.py", line 15, in from ._session import ( File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api_session.py", line 16, in import boto3 # type: ignore[import] File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\boto3__init__.py", line 17, in from boto3.session import Session File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\boto3\session.py", line 17, in import botocore.session File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\botocore\session.py", line 26, in import botocore.client File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\botocore\client.py", line 151 if auth := service_model.metadata.get('auth'): ^ SyntaxError: invalid syntax
> 
> And:
> 
> Failed to load deadline.nuke_submitter. Reason: Traceback (most recent call last): File "C:\Users\miggy\Downloads\aws_deadline_cloud\deadline-cloud-for-nuke\src/menu.py", line 16, in from deadline.nuke_submitter import ( File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter__init__.py", line 5, in from .deadline_submitter_for_nuke import show_nuke_render_submitter_noargs File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter\deadline_submitter_for_nuke.py", line 12, in from deadline.client.api import get_deadline_cloud_library_telemetry_client File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api__init__.py", line 37, in from ._loginout import login, logout File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api_loginout.py", line 15, in from ._session import ( File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\api_session.py", line 76, in @lru_cache File "C:\Program Files\Nuke13.2v9\lib\functools.py", line 490, in lru_cache raise TypeError('Expected maxsize to be an integer or None') TypeError: Expected maxsize to be an integer or None
> 
> And:
> 
> Failed to load deadline.nuke_submitter. Reason: Traceback (most recent call last): File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke/menu.py", line 16, in from deadline.nuke_submitter import ( File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter__init__.py", line 5, in from .deadline_submitter_for_nuke import show_nuke_render_submitter_noargs File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\nuke_submitter\deadline_submitter_for_nuke.py", line 15, in from deadline.client.ui.dialogs.submit_job_to_deadline_dialog import ( # type: ignore File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\ui\dialogs\submit_job_to_deadline_dialog.py", line 41, in from ..widgets.host_requirements_tab import HostRequirementsWidget File "C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\deadline\client\ui\widgets\host_requirements_tab.py", line 10, in from qtpy.QtGui import QFont, QValidator, QIntValidator, QBrush, QIcon, QRegularExpressionValidator # type: ignore ImportError: cannot import name 'QRegularExpressionValidator' from 'qtpy.QtGui' (C:\Users\miggy\DeadlineCloudSubmitter/Submitters/Nuke\qtpy\QtGui.py)
> 
> ### Reproduction Steps
> Install Deadline/Nuke submitter using development.md instructions.
> 
> Then manually 'patch' the walrus operator to use non-walrus syntax. Then you run into the QT depenency issue.
> 
> ### Code Snippet
> None.

Based on the README, the submitter needs Nuke 15. After talking with the team, the submitter for Nuke 13 is not supported.

**Comment by gpl-nickallevato** [comment]
Nuke 13 need to be supported. 
The industry dictates the requirements, not the service provider.

**Comment by rickrams** [comment]
We (the Deadline Cloud service team) definitely want customers to be able to bring any and all software they want to use with Deadline Cloud!  

The integrated Nuke submitter that's part of this repository has a dependency on Python >= 3.9 that makes it incompatible with Nuke 13 which uses Python 3.7. It is potentially possible for you to port it manually to an earlier version of boto3 (keeping in mind earlier versions of boto3 before Deadline Cloud release don't include it and service support would need to be manually ported back) and use it with Python 3.7. 

Our general recommendation - for less effort and complexity - would be to look first at submitting standalone job bundles (https://github.com/aws-deadline/deadline-cloud-samples/tree/mainline/job_bundles) that invoke Nuke directly. There will be some differences in features and experience going this route but it is the path to running _almost_ any piece of software on Deadline Cloud.

**Comment by MarinMaksutaj** [comment]
No action to be taken from this issue, closing it out.
